# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Select the FIRST-priority interface on the dedicated server to bridge.
VM_INTERFACES = %x( VBoxManage list bridgedifs | grep ^Name ).gsub(/Name:\s+/, '').split("\n")

# Get the available physical CPU cores on host system, inspired by
# https://coderwall.com/p/ghbzhw
#
HW_CPUS = RbConfig::CONFIG['host_os'] =~ /darwin/ ?
    %x( sysctl -n hw.physicalcpu_max ) :
    %x( nproc )

# The guest system only uses half of physical CPU cores of host system.
VBOX_CPU = (HW_CPUS.to_i / 2).to_s

# Hostname for guest system
VBOX_NAME = File.basename(Dir.getwd)

# Extra public/bridged ethernet interface for guest system
VBOX_NETIF = VM_INTERFACES[0]

# Default workspace folder.
VBOX_DEFAULT_WORKSPACE = "../../../../t2t/#{VBOX_NAME}"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Using Ubuntu 14.04 custom build as base.
  #
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  config.vm.hostname = VBOX_NAME

  # Enable `vagrant-cachier` to cache APT packages for multiple machine
  # environment.
  #
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.auto_detect = true
  else
    # only display the tips on vagrant up
    if ARGV[0] == "up"
      puts "[information] recommended vagrant plugin 'vagrant-cachier' plugin was not found"
      puts "[information] 'vagrant-cachier' will speed up repeated provisioning operations"
      puts "[information] install the plugin with command 'vagrant plugin install vagrant-cachier'"
    end
  end

  # Add forwarding port
  # config.vm.network :forwarded_port, guest: 4000, host: 4000
  # config.vm.network :forwarded_port, guest: 35729, host: 35729

  # Add a public/bridged ethernet interface.
  config.vm.network :public_network, :bridge => VBOX_NETIF

  # Share current repository at top.
  config.vm.synced_folder "../../", "/myboxes"

  # Share workspace path if environment variable `WORKSPACE_PATH` is available.
  if ENV.has_key?('WORKSPACE_PATH')
    config.vm.synced_folder ENV['WORKSPACE_PATH'], "/workspaces"
  else
    if File.directory?(VBOX_DEFAULT_WORKSPACE)
      config.vm.synced_folder VBOX_DEFAULT_WORKSPACE, "/workspaces"
      config.vm.synced_folder VBOX_DEFAULT_WORKSPACE, "/opt/#{VBOX_NAME}"
    else
      puts "[warning] #{VBOX_DEFAULT_WORKSPACE} doesn't exist"
    end
  end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    vb.gui = false

    vb.customize ["modifyvm", :id, "--cpus", VBOX_CPU]
    vb.customize ["modifyvm", :id, "--memory", "1024"]


    # Utilize Vagrant to mount extra disk
    #
    if Vagrant.has_plugin?("vagrant-persistent-storage")
      config.persistent_storage.enabled = true
      config.persistent_storage.location = "#{Dir.getwd}/#{VBOX_NAME}_docker_data.vdi"
      config.persistent_storage.size = 50000
      config.persistent_storage.mountname = 'dockerdata'
      config.persistent_storage.filesystem = 'ext4'
      config.persistent_storage.mountpoint = '/var/lib/docker'
      # config.persistent_storage.volgroupname = 'myvolgroup'
    else
      puts "[error] missing critical vagrant plugin: vagrant-persistent-storage"
    end
  end

  # Initialize the box.
  #
  config.vm.provision "shell", path: "../../scripts/init_#{VBOX_NAME}.sh"
end
