# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Hostname for guest system
VBOX_NAME = File.basename(Dir.getwd)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Using Ubuntu 14.04.1 custom build as base.
  #
  config.vm.box = "ffuenf/ubuntu-14.04.1-server-amd64"

  # Box base name
  #
  config.vm.hostname = VBOX_NAME

  # Add a public/bridged ethernet interface.
  # config.vm.network :public_network, :bridge => VBOX_NETIF

  # Share current repository at top.
  config.vm.synced_folder "../../", "/myboxes"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    vb.gui = false
  end

  # Initialize the box.
  #
  config.vm.provision "shell", inline: "sudo /myboxes/scripts/init.sh"

  # Clean-up unnecessary packages and temporary files
  #
  config.vm.provision "shell", inline: "sudo apt-get clean"
  config.vm.provision "shell", inline: "sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*"
end
